---
apiVersion: v1
kind: Service
metadata:
  name: my-kafka-controller-headless
  namespace: default
spec:
  publishNotReadyAddresses: true
  ports:
  - name: interbroker
    port: 9093
    targetPort: 9093
  - name: client
    port: 9092
    targetPort: 9092
  clusterIP: None
  selector:
    app.kubernetes.io/name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: my-kafka
  namespace: default
spec:
  ports:
  - name: client
    port: 9092
    targetPort: 9092
  selector:
    app.kubernetes.io/name: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-kafka-controller
  namespace: default
spec:
  serviceName: my-kafka-controller-headless
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - postgresql
                  - kafka
              topologyKey: kubernetes.io/hostname
      containers:
      - name: kafka
        image: bitnamilegacy/kafka:3.5.1
        command:
        - bash
        - -ec
        - |
          export KAFKA_CFG_NODE_ID=${HOSTNAME##*-}
          echo "Starting Kafka with short-name resolution..."
          exec /opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh
        ports:
        - containerPort: 9092
          name: client
        - containerPort: 9093
          name: interbroker
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_ENABLE_KRAFT
          value: "yes"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://$(POD_NAME).my-kafka-controller-headless.default.svc.cluster.local:9092"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "0@my-kafka-controller-0.my-kafka-controller-headless.default.svc.cluster.local:9093,1@my-kafka-controller-1.my-kafka-controller-headless.default.svc.cluster.local:9093,2@my-kafka-controller-2.my-kafka-controller-headless.default.svc.cluster.local:9093,3@my-kafka-controller-3.my-kafka-controller-headless.default.svc.cluster.local:9093"
        - name: KAFKA_CFG_NUM_PARTITIONS
          value: "100"
        - name: KAFKA_KRAFT_CLUSTER_ID
          value: "r4YzRQ3DQOaHcxK9M9z6XQ"
        volumeMounts:
        - name: data
          mountPath: /bitnami/kafka
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 8Gi