apiVersion: v1
data:
  application.yml: "server:\r\n  port: 8080\r\n  tomcat:\r\n    max-connections: 10000\r\n
    \   accept-count: 200 # Load shedding: reject connection if backlog exceeds 200\r\n
    \   threads:\r\n      max: 800\r\n      min-spare: 100\r\n  connection-timeout:
    2000ms # Fast fail instead of hanging\r\n\r\nspring:\r\n  threads:\r\n    virtual:\r\n
    \     enabled: true\r\n  jackson:\r\n    serialization:\r\n      write-dates-as-timestamps:
    false\r\n  application:\r\n    name: api-gateway\r\n  datasource:\r\n    # IMPORTANT:
    Ensure ${DB_HOST} is passed as 'pgbouncer-service' in your deployment.yaml!\r\n
    \   url: jdbc:postgresql://${DB_HOST:postgres-postgresql}:5432/${DB_NAME:postgres}\r\n
    \   username: ${DB_USER:postgres}\r\n    password: ${DB_PASSWORD:adminpassword}\r\n
    \   driver-class-name: org.postgresql.Driver\r\n    hikari:\r\n      maximum-pool-size:
    20  # Reduced to prevent DB explosion at 80 pods\r\n      connection-timeout:
    20000\r\n      max-lifetime: 600000\r\n      keepalive-time: 300000\r\n  jpa:\r\n    hibernate:\r\n      ddl-auto: none\r\n    show-sql: false\r\n
    \   properties:\r\n      hibernate:\r\n        dialect: org.hibernate.dialect.PostgreSQLDialect\r\n
    \ data:\r\n    redis:\r\n      # Fixed for Kubernetes internal DNS\r\n      host:
    ${REDIS_HOST:redis-master} \r\n      port: 6379\r\n  kafka:\r\n    # Fixed for
    Kubernetes internal DNS\r\n    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:my-kafka:9092}\r\n
    \   producer:\r\n      key-serializer: org.apache.kafka.common.serialization.StringSerializer\r\n
    \     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer\r\n
    \     retries: 3\r\n      batch-size: 32768\r\n      buffer-memory: 33554432\r\n
    \     properties:\r\n        spring.json.add.type.headers: false\r\n        linger.ms:
    2\r\n        acks: \"1\"                  # Added for throughput\r\n        compression.type:
    lz4      # Added to save network bandwidth\r\n        request.timeout.ms: 2000\r\n
    \       delivery.timeout.ms: 3000\r\n\r\npayment:\r\n  kafka:\r\n    topic:\r\n
    \     initiated: payment_initiated"
kind: ConfigMap
metadata:
  name: api-gateway-config

