apiVersion: apps/v1
kind: Deployment
metadata:
  name: clearing-service
  labels:
    app: clearing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clearing-service
  template:
    metadata:
      labels:
        app: clearing-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: clearing-service
              topologyKey: kubernetes.io/hostname
      containers:
      - name: clearing-service
        image: tricko98/clearing-service:v1
        imagePullPolicy: Always
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "my-kafka:9092"
        ports:
        - containerPort: 8083
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: clearing-service
spec:
  selector:
    app: clearing-service
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP
