apiVersion: apps/v1
kind: Deployment
metadata:
  name: clearing-service
  labels:
    app: clearing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clearing-service
  template:
    metadata:
      labels:
        app: clearing-service
    spec:
      containers:
      - name: clearing-service
        image: tricko98/clearing-service:v1
        imagePullPolicy: Always
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "my-kafka-controller-0.my-kafka-controller-headless.default.svc.cluster.local:9092"
        ports:
        - containerPort: 8083
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: clearing-service
spec:
  selector:
    app: clearing-service
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP
