apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence-worker
  labels:
    app: persistence-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: persistence-worker
  template:
    metadata:
      labels:
        app: persistence-worker
    spec:
      nodeSelector: {}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: persistence-worker
      containers:
      - name: persistence-worker
        image: tricko98/persistence-worker:v2
        imagePullPolicy: Always
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "my-kafka:9092"
        - name: SHARD0_DATASOURCE_URL
          value: "jdbc:postgresql://pgbouncer-service:5432/postgres"
        - name: SHARD0_DATASOURCE_USERNAME
          value: "postgres"
        - name: SHARD0_DATASOURCE_PASSWORD
          value: "adminpassword"
        # ── Shard 1 ──
        - name: SHARD1_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-shard-1:5432/postgres"
        - name: SHARD1_DATASOURCE_USERNAME
          value: "postgres"
        - name: SHARD1_DATASOURCE_PASSWORD
          value: "adminpassword"
        # ── Shard 2 ──
        - name: SHARD2_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-shard-2:5432/postgres"
        - name: SHARD2_DATASOURCE_USERNAME
          value: "postgres"
        - name: SHARD2_DATASOURCE_PASSWORD
          value: "adminpassword"
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
