apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement-service
  labels:
    app: settlement-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settlement-service
  template:
    metadata:
      labels:
        app: settlement-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: settlement-service
              topologyKey: kubernetes.io/hostname
      containers:
      - name: settlement-service
        image: tricko98/settlement-service:v1
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKERS
          value: "my-kafka:9092"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
